Update fxmanifest.lua
Qbox-project/qbx-medical pull request #21
Opened 2023-08-26 02:41 UTC by mockdot

Added load-unload.lua so that health states work correctly

2023-08-26 06:55 UTC, Manason approved these changes

2023-08-26 14:53 UTC, Manason requested changes

2023-08-26 14:53 UTC, Manason commented on fxmanifest.lua
> +    'load-unload.lua'
Oh. This is just in the wrong place. Move load-unload.lua into the client folder instead of changing the fxmanifest.lua :)

2023-08-26 22:12 UTC, Manason approved these changes

2023-08-27 14:47 UTC, FjamZoo approved these changes

2023-08-27 14:48 UTC, merged